<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-body">
                <?php echo (isset($this->alert) ? $this->alert : '' ); ?>
                <form action="<?php echo BASE; ?>cadastro/cadastrar/" class="form-horizontal" method="post">
                  <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Nome:</label>
                    <div class="col-sm-10">
                      <input required type="text" name="name" class="form-control" id="name" placeholder="Nome" value="<?php echo $this->request->post('name') ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">E-mail:</label>
                    <div class="col-sm-10">
                      <input required type="email" name="email" class="form-control" id="email" placeholder="seuemail@site.com.br" value="<?php echo $this->request->post('email') ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">Usuário:</label>
                    <div class="col-sm-10">
                      <input required type="text" name="username" class="form-control" id="username" placeholder="Usuário" value="<?php echo $this->request->post('usarname') ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">Senha:</label>
                    <div class="col-sm-10">
                      <input required type="password" name="password" class="form-control" id="password" placeholder="Sua senha">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div>
                  </div>
                </form>
            </div>
        </div>
    </div>
</div>
