<div class="container">
    <div class="textos">
        <ul class="social">
                <br><p>Olá!<br> Seja bem vindo ao nosso site. Aqui disponibilizamos para você,
                 de uma forma simples e prática, uma maneira de você, estudante de graduação,
                  expressar sua opinião e avaliar professores universitários da graduação com base em sua própria 
                  experiência na disciplina. É muito importante que você seja imparcial e avalie sinceramente os
                   aspectos que forem apresentados. Nosso objetivo é contribuir com a comunidade acadêmica compartilhando
                    informações que são úteis ao longo de sua trajetória como universitário. Cadastre-se agora mesmo
                     e participe desse ciclo.<br><br></p>
        </ul>       
        <a href="<?php echo BASE; ?>cadastro" class="botao medio wow wobble" data-wow-duration="1s" data-wow-delay="1s">CADASTRE-SE</a>
    </div>
</div>
