<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div align="center" class="panel-body">
               <br><br><p class="bg-danger"><i class="fa  fa-close"></i> Você já votou neste professor! </p>
               <br><br><a href="<?php echo BASE . 'voto/'; ?>" class="btn btn-primary"><i class="fa fa-reply"></i> Voltar</a>
            </div>
        </div>
    </div>
</div>
