<section class="professor">
        <div class="container" align="center">
          <ul>
            <li>
              <figure>
                <br><img src="<?php echo IMG ?>josemaria.jpg" alt="Thumb">
                <figcaption>
                  <a href="<?php echo BASE ?>voto/votacao" class="btn btn-primary">José Maria Monteiro</a><br>
                  <div class="overlay"></div>
                </figcaption>
              </figure>
            </li>

            <li>
              <figure >
                <br><img src="<?php echo IMG ?>emanuel.jpg" alt="Thumb">
                <figcaption>
                  <a href="<?php echo BASE ?>voto/votacao2" class="btn btn-primary">Emanuel Bezerra</a><br>
                  <div class="overlay"></div>
                </figcaption>
              </figure>
            </li>

            <li>
              <figure>
                <br><img src="<?php echo IMG ?>marcelino.jpg" alt="Thumb">
                <figcaption>
                  <a href="<?php echo BASE ?>voto/votacao3" class="btn btn-primary">Marcelino Pequeno</a><br>
                  <div class="overlay"></div>
                </figcaption>
              </figure>
            </li>
          </ul>
          <a href="<?php echo BASE . 'home/'; ?>" class="btn btn-primary"><i class="fa fa-reply"></i> Voltar</a>
      </div>
</section>
