<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div align="center" class="panel-body">
            	<br><br><p class="bg-success"><i class="fa  fa-check"></i> Sua votação foi realizada com sucesso !</p>
            	<br><br><a href="<?php echo BASE . 'voto/'; ?>" class="btn btn-primary"><i class="fa fa-reply"></i> Voltar</a>
            </div>
        </div>
    </div>
</div>
