<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title><?php echo $view_title; ?></title>
    <link rel="shortcut icon" href="<?php echo IMG; ?>logo-rodape.png" type="image/x-icon">
    <meta name="viewport" content="width=device-width,
    initial-scale=1">
    <link rel="stylesheet"  href="<?php echo CSS; ?>geral.css">
    <link rel="stylesheet"  href="<?php echo BOWER; ?>/wow/css/libs/animate.css">
    <link rel="stylesheet"  href="<?php echo CSS; ?>plugins.css">
    <link rel="stylesheet"  href="<?php echo CSS; ?>estrela.css">
    <link rel="stylesheet"  href="<?php echo CSS; ?><?php echo $view_title; ?>.css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">

    
    <script src= "<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
</head>
<body>

    <nav class="menu-responsivo">
        <ul>
            <li><a href="<?php echo BASE; ?>index">Início</a></li>
            <li><a href="<?php echo BASE; ?>cadastro">Cadastro</a></li>
            <li><a href="<?php echo BASE; ?>login">Login</a></li>
            <li><a href="<?php echo BASE; ?>contato">Contato</a></li>     
        </ul>
    </nav>

    <div class="layout">
        <header>
            <div class="container">
                <div class="logo wow slideInLeft" data-wow-duration="1s" data-wow-delay="1s">
                <a href="<?php echo BASE; ?>home/"">
                    <img src="<?php echo IMG; ?>logo-topo2.png" alt="Logo Topo ADK">
                </a>
                </div>  
                <div class="links"> 
                   
                    <nav class="wow fadeInDown" data-wow-duration="1s" data-wow-delay="0.3s">
                        <ul>
                            <li><a href="<?php echo BASE; ?>index">Início</a></li>
                            <li><a href="<?php echo BASE; ?>cadastro">Cadastro</a></li>
                            <li><a href="<?php echo BASE; ?>login">Login</a></li>
                            <li><a href="<?php echo BASE; ?>contato">Contato</a></li>                          
                        </ul>
                    </nav>
                    
                <a class="toggle" href="javascript:;">
                    <span></span>
                    <span></span>
                    <span></span>
                </a>


                    <ul class="social wow fadeInDown" data-wow-duration="1s" data-wow-delay="0.3s">
                        <li>
                            <a href="https://github.com/alanspontes/projeto-final-de-redes/tree/master" target="_blank"><i class="fa fa-github-alt" ></i></a>
                        </li>
                    </ul>
                </div>
                <h1><strong><?php echo $view_title; ?></strong></h1>
            </div>
        </header>
        <main>